# Generated by Django 4.2.1 on 2023-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamCatcher', '0003_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(max_length=25),
        ),
    ]
